name: 1. Extrator Play Store (Completar Firebase)

on:
  workflow_dispatch:
    inputs:
      id_jogo:
        description: 'ID do jogo no Firebase (ex: 8-ball-pool, fr-legends)'
        required: true
        default: '8-ball-pool'

jobs:
  extrair-e-salvar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Dependências
        run: npm install google-play-scraper axios

      - name: Executar Extrator Inteligente
        env:
          ID_JOGO: ${{ github.event.inputs.id_jogo }}
        run: node scraper.js
