name: 1. Extrator Play Store (Atualizar Firebase)

on:
  schedule:
    - cron: '0 0 * * *' # Roda diariamente
  workflow_dispatch: # Permite rodar manualmente a qualquer hora

jobs:
  extrair:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código
        uses: actions/checkout@v4

      - name: Configurar Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Dependências
        run: npm install

      - name: Executar Extrator
        run: node scraper.js
