name: Executar Scraper Diário

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite (UTC)
  workflow_dispatch: # Permite rodar manualmente no GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js (v20 LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Executar Scraper
        run: node scraper.js
